from .impl.adagrad import AdaGradClassifier
from .impl.primal_cd import CDClassifier
from .impl.fista import FistaClassifier
from .impl.prox_sdca import ProxSDCA_Classifier
from .impl.sparsa import SparsaClassifier
from .impl.sag import SAGClassifier
from .impl.sgd import SGDClassifier
from .impl.svrg import SVRGClassifier
from .impl.dual_cd import LinearSVC
from .impl.primal_newton import KernelSVC
